services:
  # --- BANCO DE DADOS LOCAL (Para a Aplicação Java) ---
  db-app:
    image: postgres:16-alpine
    container_name: auraskill-db-app
    restart: always
    environment:
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      POSTGRES_DB: ${APP_DB_NAME}
    ports:
      - "${APP_DB_PORT}:5432"
    volumes:
      - ./data/app-db:/var/lib/postgresql/data
    networks:
      - auraskill-network

  # --- SERVIÇO KEYCLOAK (Conectado ao Supabase) ---
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: auraskill-keycloak
    restart: always
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL_SUPABASE}
      KC_DB_USERNAME: ${KC_DB_USER_SUPABASE}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD_SUPABASE}
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "${KC_PORT}:8080"
    networks:
      - auraskill-network

  # --- BACKEND API (Spring Boot) ---
  auraskill-api:
    image: maven:3.9-eclipse-temurin-21
    container_name: auraskill-api
    working_dir: /app
    ports:
      - "8081:8081"
    volumes:
      - /home/guiassys/devtools/repos/auraskill-api:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auraskill-db-app:5432/${APP_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${APP_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${APP_DB_PASSWORD}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://auraskill-keycloak:8080/realms/auraskill
    command: sh -c "mvn clean install -DskipTests && mvn spring-boot:run"
    depends_on:
      - db-app
      - keycloak
    networks:
      - auraskill-network

  # --- FRONTEND (Next.js) ---
  auraskill-frontend:
    image: node:20-alpine
    container_name: auraskill-frontend
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - /home/guiassys/devtools/repos/auraskill:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1
    command: sh -c "npm install && npx next dev --turbo=false"
    depends_on:
      - keycloak
      - auraskill-api
    networks:
      - auraskill-network

networks:
  auraskill-network:
    driver: bridge