name: HML Deploy

on:
  push:
    branches:
      - hml

jobs:

  deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout infra
        uses: actions/checkout@v4

      - name: Update Backend
        run: |
          cd ../aura-api
          git pull

      - name: Update Frontend
        run: |
          cd ../aura-front
          git pull

      - name: Deploy Containers
        run: |
          docker compose -f docker/hml/docker-compose.yml down
          docker compose -f docker/hml/docker-compose.yml up -d --build

