name: Infra Deploy

on:
  push:
    branches:
      - main
      - hml

jobs:
  deploy:
    name: Deploy Infrastructure Base
    runs-on: self-hosted

    steps:
      # Este passo limpa qualquer resquício que o Git não consiga limpar sozinho
      - name: Pre-checkout cleanup
        run: |
          sudo rm -rf ${{ github.workspace }}/* || true

      - name: Checkout Infra Code
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Deploy Infra Stack
        run: |
          docker compose \
            --env-file /home/guiassys/devtools/repos/aura-infra/docker/hml/.env \
            -f /home/guiassys/devtools/repos/aura-infra/docker/hml/docker-compose.yml \
            up -d db-app db-keycloak keycloak

      - name: Clean up
        run: docker image prune -f